import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

# add current directory's file recursively
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
