from building import * 

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = []

# add MultiButton common include
inc = inc + [cwd]

# add MultiButton basic code
src = src + ['./multi_button.c']

# add MultiButton Test code
if GetDepend('MULTIBUTTON_USING_EXAMPLE_CALLBACK'):
    src = src + ['./examples/example_callback.c']
if GetDepend('MULTIBUTTON_USING_EXAMPLE_POLL'):
    src = src + ['./examples/example_poll.c']

# add group to IDE project
group = DefineGroup('MultiButton', src, depend = ['OFFLINE_PKG_USING_MULTIBUTTON'], CPPPATH = inc)

Return('group')
